apiVersion: v1
kind: Service
metadata:
   name: nodejs-app-svc
spec:
   type: NodePort
   selector:
      app: nodejs-app
   ports:
      - port: 8081
        targetPort: 8081
        nodePort: 30001
