---
apiVersion: apps/v1
 # Specifying the kind as Deployment
 # because we want to deploy our application
kind: Deployment
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
       # Specify your DockerHub image
        image: nimishjoseph/nodejssep:latest
        ports:
         # Exposed PORT
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
   name: nodejs-app-svc
spec:
   type: NodePort
   selector:
      app: nodejs-app
   ports:
      - port: 8081
        targetPort: 8081
        nodePort: 30001
